# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2ac62d1b1adc188a6aab696452b6a4f9cbcac24469940ce181414cc37e380d7a0320cb5a87b0628140218a7d7b7c87736ce76fd85397bc364b1d23243da3d60

test:
  secret_key_base: 534fd3ce6f0b32191537e8a2c28f0fcd21381b52c98ae5347bbcc3a8405568234b60d1275b36a023a59a373320fc79c4c6345acd694116289d0ecc05c8883989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
